# Generated by Django 2.0.2 on 2018-03-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название каталога')),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.IntegerField(verbose_name='Цена продукта')),
                ('mass', models.IntegerField(verbose_name='Вес продукта')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото продукта')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Catalog', verbose_name='Каталога')),
            ],
        ),
    ]
